### ISSUE TITLE
upper and lower bounds of universe of discourse

### ISSUE THREAD

**Issue by mridho-rmdhn** [PYFTS/notebooks#3]
hello, i want ask you something. You use the upper and lower bounds for universe of discourse by 10% as a default, but i want try different value. how to change it from 10% to another values?

**Comment by petroniocandido** [comment]
Hi! Sorry for the long delay. Indeed you can't choose it today. I will introduce this feature as soon as possible in the Partitioner.

**Comment by mridho-rmdhn** [comment]
thank you for the response, I would love to wait for that.

**Comment by petroniocandido** [comment]
Hi @mridho-rmdhn 

I just push a new version with this feature. In all partitioner were added three parameters:


- upper_margin: the percentage to exceed the known UoD on the upper bound. The default value is .1;
- lower_margin: the percentage to exceed the known UoD on the lower bound. The default value is .1;
- margin: the percentage to exceed the known UoD on both upper and lower bounds. The default value is .1;

Use upper and lower margins when you desire to specify different margins or use margin when you want to use the same values for both.

Let me know if you have any issues or questions.

**Comment by mridho-rmdhn** [comment]
thank you, the upgrade was very helpful
